# from here we can control the parameter's and increase the modularity and reuseability of our code 
# and produce different results from changing values from here only.

dataingestion:
  test_size : 0.5

dataPreprocessing:
  max_features : 10
  min_df : 5

modelbuilding:
  random_state : 2
  max_iter : 10
